"""added images to db

Revision ID: 391855067e63
Revises: 45b52cbf4ef6
Create Date: 2025-11-14 23:24:15.977672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '391855067e63'
down_revision: Union[str, None] = '45b52cbf4ef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('images', sa.JSON(), nullable=True))
    op.add_column('messages', sa.Column('tokens', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('meta', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'meta')
    op.drop_column('messages', 'tokens')
    op.drop_column('messages', 'images')
    # ### end Alembic commands ###
