"""added types to messages

Revision ID: d716e64748b7
Revises: d998b4fd5555
Create Date: 2025-11-15 00:25:03.518820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd716e64748b7'
down_revision: Union[str, None] = 'd998b4fd5555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('type', sa.String(length=32), nullable=True))
    op.add_column('messages', sa.Column('video_full', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('tokens_used', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'tokens_used')
    op.drop_column('messages', 'video_full')
    op.drop_column('messages', 'type')
    # ### end Alembic commands ###
