"""added miniatures for images

Revision ID: d998b4fd5555
Revises: 73a94d0fefd2
Create Date: 2025-11-14 23:52:23.365365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd998b4fd5555'
down_revision: Union[str, None] = '73a94d0fefd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('image_full', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('image_thumb', sa.Text(), nullable=True))
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('messages', 'tokens')
    op.drop_column('messages', 'images')
    op.drop_column('messages', 'meta')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('images', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('tokens', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('messages', 'image_thumb')
    op.drop_column('messages', 'image_full')
    # ### end Alembic commands ###
